server:
  port: 8080

spring:
  application:
      name: jukebox-playing

jukebox:
  clientname: jukebox-playing
  credentials:
    username: jukebox
    password: digital99
  hostname: subsonic.jukebox.lan:4040
  kafka:
    broker: kafka.jukebox.lan:9092
    clientname: now-playing
    topic: jukebox-events

management:
  endpoints:
    web:
      exposure
        include=health,info,sessions
