server:
  port: 8080

spring:
  application:
      name: scheduler

jukebox:
  clientname: digital-jukebox
  credentials:
    username: jukebox
    password: digital99
  hostname: subsonic.jukebox.lan:4040
  kafka:
    broker: kafka.jukebox.lan:9092
    clientname: now-playing
    enabled: true
    topic: jukebox-events
  random:
    hostname: random.jukebox.lan:8080
  scheduler.playlist:
    minsize: 10
    maxrandom: 100

management:
  endpoints:
    web:
      exposure
        include=health,info,sessions
