server:
  port: 8080

spring:
  application:
      name: particle

jukebox:
  clientname: digital-jukebox
  credentials:
    username: jukebox
    password: digital99
  hostname: subsonic.jukebox.lan:4040

  kafka:
    broker: kafka.jukebox.lan:9092
    clientname: particle
    enabled: true
    groupname: particle
    topic: jukebox-events

management:
  endpoints:
    web:
      exposure
        include=health,info,sessions
