server:
  port: 8080

spring:
  application:
      name: sdr-random

jukebox:
  random:
    sdr:
      frequency: 92.5
      pipename: mypipe

management:
  endpoints:
    web:
      exposure
        include=health,info,sessions
