server:
  port: 8080

spring:
  application:
      name: codecard-controller

jukebox:
  clientname: digital-jukebox
  credentials:
    username: jukebox
    password: digital99
  hostname: subsonic.jukebox.lan:4040
  randomcnt: 20


management:
  endpoints:
    web:
      exposure
        include=health,info,sessions
