package com.buddhadata.projects.jukebox.random.controller;

import com.buddhadata.projects.jukebox.random.ExternalSeedRandom;
import com.buddhadata.projects.jukebox.random.sdr.SdrRandom;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.annotation.PostConstruct;
import java.util.Random;

/**
 * Controller for returning random numbers generated by sdr
 */
@RestController()
@RequestMapping("sdr")
public class SdrRandomController {

  private Random random;

  @Value("${jukebox.random.sdr.frequency:92.5}")
  private String sdrFrequency;

  /**
   * File/pipe name from which to read.
   */
  @Value("${jukebox.random.sdr.pipename:unknown}")
  private String sdrPipeName;


  @GetMapping ("/boolean")
  public boolean getNextBoolean() {
    return random.nextBoolean();
  }

  @GetMapping ("/double")
  public double getNextDouble() {
    return random.nextDouble();
  }

  @GetMapping ("/float")
  public float getNextFloat() {
    return random.nextFloat();
  }

  @GetMapping("/int")
  public int getNextInteger() {
    return random.nextInt();
  }

  @GetMapping("int/{bound}")
  public int getNextInteger (@PathVariable("bound") int bound) {
    return random.nextInt (bound);
  }


  /**
   * Post-create steps to setup the controller before use, in this case creating the random number generator.
   */
  @PostConstruct
  public void init() {

    //  Create the seed producer
    SdrRandom sdr = new SdrRandom (sdrFrequency, sdrPipeName);
    sdr.start();
    random = new ExternalSeedRandom(sdr);
  }
}
